[package]
name = "common"
version = "0.1.0"
authors = ["Eduardo Yuschuk <eduardo.yuschuk@gmail.com>"]

[dependencies]
configuration = { path = "../configuration" }
time = "0.1.40"
datetime = "0.4.7"
serde = "1.0.71"
serde_derive = "1.0.71"
bincode = "1.0.1"
enum_primitive = "0.1.1"
num = "0.2.0"